export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_RESET = "CREATE_CATEGORY_RESET";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";